/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package com.mycompany.proyect;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author jose
 */
public class JDialogAnadirUsuario extends javax.swing.JDialog {

    private DefaultTableModel m;

    public JDialogAnadirUsuario(java.awt.Frame parent, boolean modal, DefaultTableModel m) {
        super(parent, modal);
        this.m = m;
        initComponents();
    }
    
    private void anadeusuaiosBBDD(){
        try{
            Class.forName("com.mysql.cj.jdbc.Driver");
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3307/biblioteca","root","");
            System.out.println("ConectadoAnadirUsuario");
            String query = String.format("INSERT INTO usuarios (NOMBRE, APELLIDOS, DNI, DOMICILIO, TELEFONO) VALUES(\"%s\", \"%s\", \"%s\", \"%s\", \"%s\");", jTextFieldJDiaAnaUsuNombre.getText(), jTextFieldJDiaAnaUsuApellidos.getText(), jTextFieldJDiaAnaUsuDni.getText(),jTextFieldJDiaAnaUsuDomicilio.getText(), jTextFieldJDiaAnaUsuTelefono.getText());
            PreparedStatement rs = con.prepareStatement(query);
            m.setRowCount(m.getRowCount());
            int rowCount = rs.executeUpdate();

            m.addRow(new Object[]{jTextFieldJDiaAnaUsuNombre.getText(), jTextFieldJDiaAnaUsuApellidos.getText(), jTextFieldJDiaAnaUsuDni.getText(),jTextFieldJDiaAnaUsuDomicilio.getText(), jTextFieldJDiaAnaUsuTelefono.getText()});
            
            rs.close();
            con.close();
        }catch(Exception ex){
            System.out.println("No Conectado. Error:");
            ex.printStackTrace();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelDiaAgreUsu = new javax.swing.JLabel();
        jLabelJdiaAnaUsuNombre = new javax.swing.JLabel();
        jLabelJdiaAnaUsuDni = new javax.swing.JLabel();
        jLabelJdiaAnaUsuApellido1 = new javax.swing.JLabel();
        jLabelJdiaAnaUsuDomicilio = new javax.swing.JLabel();
        jLabelJdiaAnaUsuTelefono = new javax.swing.JLabel();
        jTextFieldJDiaAnaUsuNombre = new javax.swing.JTextField();
        jTextFieldJDiaAnaUsuApellidos = new javax.swing.JTextField();
        jTextFieldJDiaAnaUsuDni = new javax.swing.JTextField();
        jTextFieldJDiaAnaUsuDomicilio = new javax.swing.JTextField();
        jTextFieldJDiaAnaUsuTelefono = new javax.swing.JTextField();
        jButtonJDiaAnaUsuEnviar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabelDiaAgreUsu.setFont(new java.awt.Font("Segoe Print", 1, 14)); // NOI18N
        jLabelDiaAgreUsu.setText("Añadir Usuario");

        jLabelJdiaAnaUsuNombre.setText("nombre");

        jLabelJdiaAnaUsuDni.setText("DNI");

        jLabelJdiaAnaUsuApellido1.setText("Apellidos");

        jLabelJdiaAnaUsuDomicilio.setText("Domicilio");

        jLabelJdiaAnaUsuTelefono.setText("Telefono");

        jButtonJDiaAnaUsuEnviar.setText("Enviar");
        jButtonJDiaAnaUsuEnviar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonJDiaAnaUsuEnviarMouseClicked(evt);
            }
        });
        jButtonJDiaAnaUsuEnviar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonJDiaAnaUsuEnviarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabelJdiaAnaUsuDni, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabelJdiaAnaUsuNombre, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabelJdiaAnaUsuApellido1, javax.swing.GroupLayout.DEFAULT_SIZE, 70, Short.MAX_VALUE)
                            .addComponent(jLabelJdiaAnaUsuDomicilio, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabelJdiaAnaUsuTelefono, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(26, 26, 26)
                                .addComponent(jLabelDiaAgreUsu, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTextFieldJDiaAnaUsuApellidos, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextFieldJDiaAnaUsuNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextFieldJDiaAnaUsuDni, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextFieldJDiaAnaUsuDomicilio, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextFieldJDiaAnaUsuTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(151, 151, 151)
                        .addComponent(jButtonJDiaAnaUsuEnviar)))
                .addContainerGap(56, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabelDiaAgreUsu)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelJdiaAnaUsuNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldJDiaAnaUsuNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelJdiaAnaUsuApellido1, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldJDiaAnaUsuApellidos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelJdiaAnaUsuDni, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldJDiaAnaUsuDni, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelJdiaAnaUsuDomicilio, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldJDiaAnaUsuDomicilio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelJdiaAnaUsuTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldJDiaAnaUsuTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jButtonJDiaAnaUsuEnviar)
                .addContainerGap(8, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonJDiaAnaUsuEnviarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonJDiaAnaUsuEnviarActionPerformed
        anadeusuaiosBBDD();
        dispose();
    }//GEN-LAST:event_jButtonJDiaAnaUsuEnviarActionPerformed

    private void jButtonJDiaAnaUsuEnviarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonJDiaAnaUsuEnviarMouseClicked
        
    }//GEN-LAST:event_jButtonJDiaAnaUsuEnviarMouseClicked

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonJDiaAnaUsuEnviar;
    private javax.swing.JLabel jLabelDiaAgreUsu;
    private javax.swing.JLabel jLabelJdiaAnaUsuApellido1;
    private javax.swing.JLabel jLabelJdiaAnaUsuDni;
    private javax.swing.JLabel jLabelJdiaAnaUsuDomicilio;
    private javax.swing.JLabel jLabelJdiaAnaUsuNombre;
    private javax.swing.JLabel jLabelJdiaAnaUsuTelefono;
    private javax.swing.JTextField jTextFieldJDiaAnaUsuApellidos;
    private javax.swing.JTextField jTextFieldJDiaAnaUsuDni;
    private javax.swing.JTextField jTextFieldJDiaAnaUsuDomicilio;
    private javax.swing.JTextField jTextFieldJDiaAnaUsuNombre;
    private javax.swing.JTextField jTextFieldJDiaAnaUsuTelefono;
    // End of variables declaration//GEN-END:variables
}
