/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package com.mycompany.proyect;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import javax.swing.table.DefaultTableModel;
import java.lang.Object;
import java.util.Vector;
/**
 *
 * @author jose
 */
public class JDialogEditarUsuario extends javax.swing.JDialog {

    private DefaultTableModel m;
    private String dni;
    private int columna;

    public JDialogEditarUsuario(java.awt.Frame parent, boolean modal, DefaultTableModel m, String dni, int colum) {
        super(parent, modal);
        this.m = m;
        this.dni = dni;
        this.columna = colum;
        initComponents();
        jTextFieldJDiaEdiUsuNombre.setText(m.getValueAt(colum, 0)+"");
        jTextFieldJDiaEdiUsuApellidos.setText(m.getValueAt(colum, 1)+"");
        jTextFieldJDiaEdiUsuDni.setText(m.getValueAt(colum, 2)+"");
        jTextFieldJDiaEdiUsuDomicilio.setText(m.getValueAt(colum, 3)+"");
        jTextFieldJDiaEdiUsuTelefono.setText(m.getValueAt(colum, 4)+"");        
    }
    
    private void editaLibroBBDD(){
        try {
            Class.forName("com.mysql.cj.jdbc.Driver");
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3307/biblioteca", "root", "");
            con.setAutoCommit(false);
            
            System.out.println("Conectado");
            
            String updateQuery = "UPDATE usuarios SET NOMBRE = ?, APELLIDOS = ?, DNI = ?, DOMICILIO = ?, TELEFONO = ? where DNI = ?;";
            PreparedStatement preparedStatement = con.prepareStatement(updateQuery);

            preparedStatement.setString(1, jTextFieldJDiaEdiUsuNombre.getText());
            preparedStatement.setString(2, jTextFieldJDiaEdiUsuApellidos.getText());
            preparedStatement.setString(3, jTextFieldJDiaEdiUsuDni.getText());
            preparedStatement.setString(4, jTextFieldJDiaEdiUsuDomicilio.getText());
            preparedStatement.setInt(5, Integer.parseInt(jTextFieldJDiaEdiUsuTelefono.getText()));
            preparedStatement.setString(6, dni);

            int rowCount = preparedStatement.executeUpdate();
            con.commit();
            m.removeRow(columna);
            m.insertRow(columna, new Object[]{jTextFieldJDiaEdiUsuNombre.getText(), jTextFieldJDiaEdiUsuApellidos.getText(), jTextFieldJDiaEdiUsuDni.getText(), jTextFieldJDiaEdiUsuDomicilio.getText(), jTextFieldJDiaEdiUsuTelefono.getText(), dni});
            preparedStatement.close();
            con.close();
            System.out.println("Filas afectadas por la actualizacion: " + rowCount);
        } catch (Exception ex) {
            System.out.println("No conectado o error al eliminar los datos");
            ex.printStackTrace();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelDiaAgreLib = new javax.swing.JLabel();
        jLabelJdiaAnaLibTitulo = new javax.swing.JLabel();
        jLabelJdiaAnaLibTipo = new javax.swing.JLabel();
        jLabelJdiaAnaLibAutor = new javax.swing.JLabel();
        jTextFieldJDiaEdiUsuNombre = new javax.swing.JTextField();
        jTextFieldJDiaEdiUsuApellidos = new javax.swing.JTextField();
        jTextFieldJDiaEdiUsuDni = new javax.swing.JTextField();
        jButtonJDiaEdiUsuEnviar = new javax.swing.JButton();
        jTextFieldJDiaEdiUsuDomicilio = new javax.swing.JTextField();
        jTextFieldJDiaEdiUsuTelefono = new javax.swing.JTextField();
        jLabelJdiaAnaLibTitulo1 = new javax.swing.JLabel();
        jLabelJdiaAnaLibAutor1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabelDiaAgreLib.setFont(new java.awt.Font("Segoe Print", 1, 14)); // NOI18N
        jLabelDiaAgreLib.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelDiaAgreLib.setText("Editar Libro");

        jLabelJdiaAnaLibTitulo.setText("Nombre");

        jLabelJdiaAnaLibTipo.setText("DNI");

        jLabelJdiaAnaLibAutor.setText("Apellidos");

        jButtonJDiaEdiUsuEnviar.setText("Enviar");
        jButtonJDiaEdiUsuEnviar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonJDiaEdiUsuEnviarMouseClicked(evt);
            }
        });
        jButtonJDiaEdiUsuEnviar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonJDiaEdiUsuEnviarActionPerformed(evt);
            }
        });

        jLabelJdiaAnaLibTitulo1.setText("Domicilio");

        jLabelJdiaAnaLibAutor1.setText("Telefono");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabelJdiaAnaLibTitulo1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabelJdiaAnaLibAutor1, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTextFieldJDiaEdiUsuTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextFieldJDiaEdiUsuDomicilio, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabelJdiaAnaLibTipo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabelJdiaAnaLibTitulo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabelJdiaAnaLibAutor, javax.swing.GroupLayout.DEFAULT_SIZE, 70, Short.MAX_VALUE))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(26, 26, 26)
                                        .addComponent(jLabelDiaAgreLib, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jTextFieldJDiaEdiUsuApellidos, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jTextFieldJDiaEdiUsuNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jTextFieldJDiaEdiUsuDni, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)))))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(156, 156, 156)
                        .addComponent(jButtonJDiaEdiUsuEnviar)))
                .addContainerGap(56, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabelDiaAgreLib)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelJdiaAnaLibTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldJDiaEdiUsuNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelJdiaAnaLibAutor, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldJDiaEdiUsuApellidos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelJdiaAnaLibTipo, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldJDiaEdiUsuDni, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelJdiaAnaLibTitulo1, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldJDiaEdiUsuDomicilio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelJdiaAnaLibAutor1, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldJDiaEdiUsuTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jButtonJDiaEdiUsuEnviar)
                .addContainerGap(29, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonJDiaEdiUsuEnviarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonJDiaEdiUsuEnviarActionPerformed
        editaLibroBBDD();
        dispose();
    }//GEN-LAST:event_jButtonJDiaEdiUsuEnviarActionPerformed

    private void jButtonJDiaEdiUsuEnviarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonJDiaEdiUsuEnviarMouseClicked
        
    }//GEN-LAST:event_jButtonJDiaEdiUsuEnviarMouseClicked

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonJDiaEdiUsuEnviar;
    private javax.swing.JLabel jLabelDiaAgreLib;
    private javax.swing.JLabel jLabelJdiaAnaLibAutor;
    private javax.swing.JLabel jLabelJdiaAnaLibAutor1;
    private javax.swing.JLabel jLabelJdiaAnaLibTipo;
    private javax.swing.JLabel jLabelJdiaAnaLibTitulo;
    private javax.swing.JLabel jLabelJdiaAnaLibTitulo1;
    private javax.swing.JTextField jTextFieldJDiaEdiUsuApellidos;
    private javax.swing.JTextField jTextFieldJDiaEdiUsuDni;
    private javax.swing.JTextField jTextFieldJDiaEdiUsuDomicilio;
    private javax.swing.JTextField jTextFieldJDiaEdiUsuNombre;
    private javax.swing.JTextField jTextFieldJDiaEdiUsuTelefono;
    // End of variables declaration//GEN-END:variables
}
