/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package com.mycompany.proyect;

import static com.mycompany.proyect.jFrameIndex.m;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author jose
 */
public class JDialogAnadirLibro extends javax.swing.JDialog {

    private DefaultTableModel m;
    private jFrameIndex jF;

    public JDialogAnadirLibro(java.awt.Frame parent, boolean modal, jFrameIndex jF) {
        super(parent, modal);
        this.m = jF.ml;
        this.jF = jF;
        initComponents();
    }
    
    private void anadeLibroBBDD(){
        try{
            Class.forName("com.mysql.cj.jdbc.Driver");
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3307/biblioteca","root","");
            System.out.println("ConectadoAnadirUsuario");
            String query = String.format("INSERT INTO libros (TITULO, AUTOR, TIPO, DISPONIBLE) VALUES(\"%s\", \"%s\", \"%s\", 1);", jTextFieldJDiaAnaLibTitulo.getText(), jTextFieldJDiaAnaLibAutor.getText(), jTextFieldJDiaAnaLibTipo.getText());
            PreparedStatement rs = con.prepareStatement(query);
            m.setRowCount(m.getRowCount());
            int rowCount = rs.executeUpdate();
            String querySelect = "SELECT (MAX(ID) + 1) AS ID FROM libros;";

            Statement stmt = con.createStatement();
            ResultSet rss = stmt.executeQuery(querySelect);
            int id = 0;
            if (rss.next())
                id = rss.getInt("ID")-1;
            else
                System.out.println("fallo en el id. poniendo el id en 1 ya que puede que se el primero");
            
            m.addRow(new Object[]{id,jTextFieldJDiaAnaLibTitulo.getText(), jTextFieldJDiaAnaLibAutor.getText(), jTextFieldJDiaAnaLibTipo.getText(), true});
            jF.preparaTablasLibDisp();
            rs.close();
            con.close();
        }catch(Exception ex){
            System.out.println("No Conectado. Error:");
            ex.printStackTrace();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelDiaAgreLib = new javax.swing.JLabel();
        jLabelJdiaAnaLibTitulo = new javax.swing.JLabel();
        jLabelJdiaAnaLibTipo = new javax.swing.JLabel();
        jLabelJdiaAnaLibAutor = new javax.swing.JLabel();
        jTextFieldJDiaAnaLibTitulo = new javax.swing.JTextField();
        jTextFieldJDiaAnaLibAutor = new javax.swing.JTextField();
        jTextFieldJDiaAnaLibTipo = new javax.swing.JTextField();
        jButtonJDiaAnaLibEnviar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabelDiaAgreLib.setFont(new java.awt.Font("Segoe Print", 1, 14)); // NOI18N
        jLabelDiaAgreLib.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelDiaAgreLib.setText("Añadir Libro");

        jLabelJdiaAnaLibTitulo.setText("Titulo");

        jLabelJdiaAnaLibTipo.setText("Tipo");

        jLabelJdiaAnaLibAutor.setText("Autor");

        jButtonJDiaAnaLibEnviar.setText("Enviar");
        jButtonJDiaAnaLibEnviar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonJDiaAnaLibEnviarMouseClicked(evt);
            }
        });
        jButtonJDiaAnaLibEnviar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonJDiaAnaLibEnviarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabelJdiaAnaLibTipo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabelJdiaAnaLibTitulo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabelJdiaAnaLibAutor, javax.swing.GroupLayout.DEFAULT_SIZE, 70, Short.MAX_VALUE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(26, 26, 26)
                                .addComponent(jLabelDiaAgreLib, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTextFieldJDiaAnaLibAutor, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextFieldJDiaAnaLibTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextFieldJDiaAnaLibTipo, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(159, 159, 159)
                        .addComponent(jButtonJDiaAnaLibEnviar)))
                .addContainerGap(56, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabelDiaAgreLib)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelJdiaAnaLibTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldJDiaAnaLibTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelJdiaAnaLibAutor, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldJDiaAnaLibAutor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelJdiaAnaLibTipo, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldJDiaAnaLibTipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jButtonJDiaAnaLibEnviar)
                .addContainerGap(39, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonJDiaAnaLibEnviarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonJDiaAnaLibEnviarActionPerformed
        anadeLibroBBDD();
        dispose();
    }//GEN-LAST:event_jButtonJDiaAnaLibEnviarActionPerformed

    private void jButtonJDiaAnaLibEnviarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonJDiaAnaLibEnviarMouseClicked
        
    }//GEN-LAST:event_jButtonJDiaAnaLibEnviarMouseClicked

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonJDiaAnaLibEnviar;
    private javax.swing.JLabel jLabelDiaAgreLib;
    private javax.swing.JLabel jLabelJdiaAnaLibAutor;
    private javax.swing.JLabel jLabelJdiaAnaLibTipo;
    private javax.swing.JLabel jLabelJdiaAnaLibTitulo;
    private javax.swing.JTextField jTextFieldJDiaAnaLibAutor;
    private javax.swing.JTextField jTextFieldJDiaAnaLibTipo;
    private javax.swing.JTextField jTextFieldJDiaAnaLibTitulo;
    // End of variables declaration//GEN-END:variables
}
