/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package com.mycompany.proyect;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import javax.swing.table.DefaultTableModel;
import java.lang.Object;
/**
 *
 * @author jose
 */
public class JDialogEditarLibro extends javax.swing.JDialog {

    private DefaultTableModel m;
    private Integer id;
    private int columna;

    public JDialogEditarLibro(java.awt.Frame parent, boolean modal, DefaultTableModel m, Integer id, int colum) {
        super(parent, modal);
        this.m = m;
        this.id = id;
        this.columna = colum;
        initComponents();
        jTextFieldJDiaEdiLibTitulo.setText(m.getValueAt(colum, 1)+"");
        jTextFieldJDiaEdiLibAutor.setText(m.getValueAt(colum, 2)+"");
        jTextFieldJDiaEdiLibTipo.setText(m.getValueAt(colum, 3)+"");
    }
    
    private void editaLibroBBDD(){
        try {
            Class.forName("com.mysql.cj.jdbc.Driver");
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3307/biblioteca", "root", "");
            con.setAutoCommit(false);
            
            System.out.println("Conectado");
            
            String updateQuery = "UPDATE libros SET TITULO = ?, AUTOR = ?, TIPO = ? where ID = ?;";
            PreparedStatement preparedStatement = con.prepareStatement(updateQuery);

            preparedStatement.setString(1, jTextFieldJDiaEdiLibTitulo.getText());
            preparedStatement.setString(2, jTextFieldJDiaEdiLibAutor.getText());
            preparedStatement.setString(3, jTextFieldJDiaEdiLibTipo.getText());
            preparedStatement.setInt(4, (int)id);

            int rowCount = preparedStatement.executeUpdate();
            con.commit();
            boolean disponible = (m.getValueAt(columna, 4)+"").equals("true");
            m.removeRow(columna);
            m.insertRow(columna, new Object[]{id, jTextFieldJDiaEdiLibTitulo.getText(), jTextFieldJDiaEdiLibAutor.getText(), jTextFieldJDiaEdiLibTipo.getText(), disponible});
            preparedStatement.close();
            con.close();
            System.out.println("Filas afectadas por la actualizacion: " + rowCount);
        } catch (Exception ex) {
            System.out.println("No conectado o error al eliminar los datos");
            ex.printStackTrace();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelDiaAgreLib = new javax.swing.JLabel();
        jLabelJdiaAnaLibTitulo = new javax.swing.JLabel();
        jLabelJdiaAnaLibTipo = new javax.swing.JLabel();
        jLabelJdiaAnaLibAutor = new javax.swing.JLabel();
        jTextFieldJDiaEdiLibTitulo = new javax.swing.JTextField();
        jTextFieldJDiaEdiLibAutor = new javax.swing.JTextField();
        jTextFieldJDiaEdiLibTipo = new javax.swing.JTextField();
        jButtonJDiaEdiLibEnviar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabelDiaAgreLib.setFont(new java.awt.Font("Segoe Print", 1, 14)); // NOI18N
        jLabelDiaAgreLib.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelDiaAgreLib.setText("Editar Libro");

        jLabelJdiaAnaLibTitulo.setText("Titulo");

        jLabelJdiaAnaLibTipo.setText("Tipo");

        jLabelJdiaAnaLibAutor.setText("Autor");

        jButtonJDiaEdiLibEnviar.setText("Enviar");
        jButtonJDiaEdiLibEnviar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonJDiaEdiLibEnviarMouseClicked(evt);
            }
        });
        jButtonJDiaEdiLibEnviar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonJDiaEdiLibEnviarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabelJdiaAnaLibTipo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabelJdiaAnaLibTitulo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabelJdiaAnaLibAutor, javax.swing.GroupLayout.DEFAULT_SIZE, 70, Short.MAX_VALUE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(26, 26, 26)
                                .addComponent(jLabelDiaAgreLib, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTextFieldJDiaEdiLibAutor, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextFieldJDiaEdiLibTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextFieldJDiaEdiLibTipo, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(159, 159, 159)
                        .addComponent(jButtonJDiaEdiLibEnviar)))
                .addContainerGap(56, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabelDiaAgreLib)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelJdiaAnaLibTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldJDiaEdiLibTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelJdiaAnaLibAutor, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldJDiaEdiLibAutor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelJdiaAnaLibTipo, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldJDiaEdiLibTipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jButtonJDiaEdiLibEnviar)
                .addContainerGap(39, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonJDiaEdiLibEnviarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonJDiaEdiLibEnviarActionPerformed
        editaLibroBBDD();
        dispose();
    }//GEN-LAST:event_jButtonJDiaEdiLibEnviarActionPerformed

    private void jButtonJDiaEdiLibEnviarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonJDiaEdiLibEnviarMouseClicked
        
    }//GEN-LAST:event_jButtonJDiaEdiLibEnviarMouseClicked

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonJDiaEdiLibEnviar;
    private javax.swing.JLabel jLabelDiaAgreLib;
    private javax.swing.JLabel jLabelJdiaAnaLibAutor;
    private javax.swing.JLabel jLabelJdiaAnaLibTipo;
    private javax.swing.JLabel jLabelJdiaAnaLibTitulo;
    private javax.swing.JTextField jTextFieldJDiaEdiLibAutor;
    private javax.swing.JTextField jTextFieldJDiaEdiLibTipo;
    private javax.swing.JTextField jTextFieldJDiaEdiLibTitulo;
    // End of variables declaration//GEN-END:variables
}
